# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Dr. Sammy Orozco - Especialista en Artroscopia y Traumatología Deportiva
email: consultoriomedico809@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Dr. Sammy Orozco, especialista en Cirugía Ortopédica, Traumatología y Artroscopia Deportiva en Cali, Colombia. 
  Tratamientos especializados en rodilla, hombro, tobillo y más con técnicas mínimamente invasivas.
keywords: artroscopia, doctor orozco, dr sammy orozco, fractura, cirugía ortopédica, hospital farallones, cali, medicina deportiva, ortopedia, prótesis de cadera, prp, traumatología, cirugía artroscópica
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sammyorozcoartroscopia.com" # the base hostname & protocol for your site
phone1: 317 583 4699
location: Centro Médico Clínica Farallones, Calle 9c # 50 - 25, Consultorio 709, Cali, Colombia
consultation_hours: Lunes a viernes 8:00 AM a 5:00 PM y Sábados 8:00 AM a 12:00 M

# Social media
social:
  name: Dr. Sammy Orozco
  links:
    # Add social media profiles when available
    # - https://twitter.com/drsammyorozco
    # - https://www.facebook.com/drsammyorozco
    # - https://www.linkedin.com/in/drsammyorozco

# SEO settings
logo: /assets/logo.png
seo:
  type: MedicalBusiness
  name: Dr. Sammy Orozco - Especialista en Artroscopia y Traumatología Deportiva
  description: Dr. Sammy Orozco, especialista en Cirugía Ortopédica, Traumatología y Artroscopia Deportiva en Cali, Colombia. Tratamientos especializados en rodilla, hombro, tobillo y más con técnicas mínimamente invasivas.
  image: /assets/sammy.jpg
  specialties:
    - Cirugía Ortopédica
    - Traumatología
    - Cirugía Artroscópica
    - Medicina Deportiva
  services:
    - name: Artroscopia de Rodilla
      type: MedicalProcedure
      description: Tratamiento mínimamente invasivo para lesiones de menisco, ligamentos y cartílago
    - name: Artroscopia de Hombro
      type: MedicalProcedure
      description: Tratamiento especializado para lesiones del hombro mediante técnicas artroscópicas
    - name: Artroscopia de Tobillo
      type: MedicalProcedure
      description: Tratamiento mínimamente invasivo para lesiones articulares del tobillo
    - name: Medicina Deportiva
      type: MedicalTherapy
      description: Tratamiento especializado de lesiones relacionadas con actividades deportivas
    - name: Plasma Rico en Plaquetas (PRP)
      type: MedicalTherapy
      description: Tratamiento regenerativo que acelera la recuperación de lesiones musculares y articulares
  address:
    streetAddress: Calle 9c # 50 - 25, Consultorio 709
    addressLocality: Cali
    addressRegion: Valle del Cauca
    addressCountry: CO
    postalCode: "760001"
  geo:
    latitude: 3.4100740975178354
    longitude: -76.54180428524194
  openingHours:
    - dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
      opens: "08:00"
      closes: "18:00"
  sameAs:
    - https://www.facebook.com/drsammyorozco
    - https://www.linkedin.com/in/drsammyorozco
    - https://twitter.com/drsammyorozco
  medicalAudience:
    - type: MedicalAudience
      audienceType: MedicalResearcher
    - type: MedicalAudience
      audienceType: MedicalPractitioner
    - type: MedicalAudience
      audienceType: Patient
  person:
    type: Person
    name: Dr. Sammy Orozco
    jobTitle: Especialista en Cirugía Ortopédica y Traumatología
    image: /assets/sammy.jpg
    alumniOf:
      - type: CollegeOrUniversity
        name: Universidad del Cauca
        description: Medicina y Cirugía
      - type: Hospital
        name: Hospital de Ortopedia y Traumatología Magdalena de las Salinas
        description: Especialista en Cirugía Ortopédica y Traumatología
      - type: CollegeOrUniversity
        name: Instituto Mexicano del Seguro Social – Universidad Nacional Autónoma de México UNAM
        description: Subespecialidad en Cirugía Artroscópica
    memberOf:
      - type: Organization
        name: Sociedad Colombiana de Cirugía de Ortopedia y Traumatología
        abbreviation: SCCOT
      - type: Organization
        name: Sociedad Colombiana de Artroscopia y Traumatología Deportiva
        abbreviation: SOCARTD
      - type: Organization
        name: Asociación Colombiana de Cirugía Artroscópica
        abbreviation: ACCART
      - type: Organization
        name: Artroscopy Association of North America
        abbreviation: AANA
      - type: Organization
        name: Sociedad Latinoamericana de Artroscopia, Rodilla y Deporte
        abbreviation: SLARD
      - type: Organization
        name: International Society of Arthroscopy, Knee Surgery and Orthopaedic Sports Medicine
        abbreviation: ISAKOS
    medicalSpecialty:
      - Cirugía Ortopédica
      - Traumatología
      - Cirugía Artroscópica
      - Medicina Deportiva
    sameAs:
      - https://www.facebook.com/drsammyorozco
      - https://www.linkedin.com/in/drsammyorozco
      - https://twitter.com/drsammyorozco

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
